### ISSUE TITLE
建议增加插件youtube

### ISSUE THREAD

**Issue by akers4238** [maotoumao/MusicFreePlugins#12]
**注意事项**
- [x] 确保已经阅读过ReadMe并*了解本软件的定位*
- [x] 确保你的新需求/想法合理合法，且*不是因为无解决方案的众口难调导致的个例问题*

------

需求描述
搜索歌曲在qq，网易，b*搜索不到，youtube可以搜到

**替代方案**
能正常搜索youtube视频即可

**其他信息**
是否能提供一些其他的帮助，包括但不限于代码、UI、测试 ... 如果有的话，辛苦描述一下，感谢~
网站m.youtube.com(链接通用不分video等分链接，最终网站指向m.youtube.com)

**Comment by kjajk6366** [comment]
同意，同意！我也在研究怎么把YT加进来

**Comment by maotoumao** [comment]
我试试~ 插件有关的问题在这个仓库提吧

**Comment by lovegaoshi** [comment]
可以参考我这个适配RN的ytm API库
https://github.com/lovegaoshi/muse/tree/apm-release
https://github.com/lovegaoshi/azusa-player-mobile/blob/master/src/utils/mediafetch/ytbsearch.ts

**Comment by maotoumao** [comment]
好了：
https://gitee.com/maotoumao/MusicFreePlugins/raw/v0.1/dist/youtube/index.js
https://raw.githubusercontent.com/maotoumao/MusicFreePlugins/master/dist/youtube/index.js

**Comment by kjajk6366** [comment]
已经安装成功了，泰裤辣，不过我发现个问题诶：
我可以用YouTube插件正常搜索歌曲，但是我想点击播放的时候，却卡着不动了，感觉是流没有读进来？

**Comment by maotoumao** [comment]
> 已经安装成功了，泰裤辣，不过我发现个问题诶： 我可以用YouTube插件正常搜索歌曲，但是我想点击播放的时候，却卡着不动了，感觉是流没有读进来？

应该只是比较慢😂
![image](https://github.com/maotoumao/MusicFreePlugins/assets/31655147/0ee54a0b-93e8-4134-8a64-74d9d7e751a5)

**Comment by kjajk6366** [comment]
> > 已经安装成功了，泰裤辣，不过我发现个问题诶： 我可以用YouTube插件正常搜索歌曲，但是我想点击播放的时候，却卡着不动了，感觉是流没有读进来？
> 
> 应该只是比较慢😂 ![image](https://private-user-images.githubusercontent.com/31655147/288084201-0ee54a0b-93e8-4134-8a64-74d9d7e751a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjcxMzgsIm5iZiI6MTcwMjM2NjgzOCwicGF0aCI6Ii8zMTY1NTE0Ny8yODgwODQyMDEtMGVlNTRhMGItOTNlOC00MTM0LThhNjQtNzRkOWQ3ZTc1MWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA3NDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZWVlMDgwYWNkZGQ4MGNlZmNiMGUyMmRkYzViOTEyMTJiYjU1YmZkM2I0NmM4ZTRjZTdhYTZkMGY5MDgxZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BVPm4Ybnknf3c8rZv8QGevvxzpqvY8wc2pOsBuhMC4)

哈哈哈，好像是的

**Comment by luo-chuan** [comment]
建议单独为这一个插件增加一个代理设置
