### ISSUE TITLE
无法订阅qq

### ISSUE THREAD

**Issue by xwshan** [maotoumao/MusicFreePlugins#42]
为啥新的订阅插进中没有了QQ，网易，酷我，咪咕？

**Comment by oldsento** [comment]
可能是接口被封或开发者被音乐源方警告了

**Comment by maotoumao** [comment]
收到了告知函，因此本示例插件仓库不再提供国内音乐厂商的源，有需要可以自己开发

https://mp.weixin.qq.com/s/NXww80a6YX4rbjwmepL48w
