### ISSUE TITLE
网易云插件 导入歌单功能没有反应

### ISSUE THREAD

**Issue by icerain9247** [maotoumao/MusicFreePlugins#6]
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/49773633/40aba3e5-7b29-4062-8410-056ce2d39c76)
![image](https://github.com/maotoumao/MusicFreeDesktop/assets/49773633/78b210b4-8b9f-42ba-a448-d39a0a0a77b2)
按照提示操作，新建歌单导入，没有新增歌曲，也没有其他提示

**Comment by maotoumao** [comment]
插件问题，网页端在我的歌单当前页链接没问题（默认歌单除外）；客户端分享链接修好了，更新下插件就好了
